@ECHO OFF
:USAGE
:START
:INITIALIZE
    SETLOCAL ENABLEDELAYEDEXPANSION
    SET BASE_DIR=%~DP0

:CODE
    SET GLOBALS_FILE=%BASE_DIR%\globals.txt
    SET TEMP_GLOBALS_FILE=%TEMP%\globals.txt

    COPY NUL %TEMP_GLOBALS_FILE% > NUL 2>&1

    FOR /F "TOKENS=1,*" %%I IN (%GLOBALS_FILE%) DO (
        SET VAR_NAME=%%I
        SET VALUE=%%J

        IF "!VAR_NAME:~0,1!" == "$" (
            SET REFERENCE=%VAR_NAME%
            CALL %GLOBALS_FILE% REFERENCE_COUNT[%REFERENCE%] REFERENCE_COUNT

            IF %REFERENCE_COUNT% GTR 0 (
                CALL SET-GLOBAL %TEMP_GLOBALS_FILE% %REFERENCE% %VALUE%
                CALL SET-GLOBAL %TEMP_GLOBALS_FILE% REFERENCE_COUNT[%REFERENCE%] %REFERENCE_COUNT%
            )
        )
    )

    TYPE %TEMP_GLOBALS_FILE% > %GLOBALS_FILE%
    DEL /S /Q %TEMP_GLOBALS_FILE% > NUL 2>&1

:RETURN
    ENDLOCAL

:EOF
