@ECHO OFF
:USAGE
:START
:INITIALIZE
    SETLOCAL ENABLEDELAYEDEXPANSION
    SET BASE_DIR=%~DP0
    SET OUT_REFERENCE=%1

:CODE
    SET HEX_DIGITS=0123456789ABCDEF
    SET DIGIT_INDEX=0
    SET MAX_INT=32767
    SET RADIX=16
    SET REFERENCE=$
    SET DIGIT=""

    FOR /L %%I IN (1,1,8) DO (
        SET /A DIGIT_INDEX="!RANDOM!*%RADIX%/(%MAX_INT% + 1)"
        CALL SET DIGIT=%%HEX_DIGITS:~!DIGIT_INDEX!,1%%
        SET REFERENCE=!REFERENCE!!DIGIT!
    )

:RETURN
    ENDLOCAL & (
        SET %OUT_REFERENCE%=%REFERENCE%
    )

:EOF
@ECHO ON
